"""mobile

Revision ID: 69f20665bc6e
Revises: e99580b6e142
Create Date: 2018-05-10 16:51:47.280586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f20665bc6e'
down_revision = 'e99580b6e142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobilenum', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_mobilenum'), 'user', ['mobilenum'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mobilenum'), table_name='user')
    op.drop_column('user', 'mobilenum')
    # ### end Alembic commands ###
